### ISSUE TITLE
Don't bundle the aws-sdk with this library.

### ISSUE THREAD

**Issue by christopher-caldwell** [montumodi/sqs-bulk-loader#16]
I was investigating using this, until I found out the [package size](https://bundlephobia.com/result?p=sqs-bulk-loader@2.13.0) is 2.7mb. Looks like 98% is bundling the aws-sdk with it. 

The sdk should probably be a peer dependency.

**Comment by montumodi** [comment]
Thanks for feedback @christopher-caldwell . This will be a breaking change so I will have to bump a major version.

**Comment by dandinu** [comment]
I support this change. When deploying to AWS Lambda it increases the warm-up time by around 1.6s.

**Comment by montumodi** [comment]
@christopher-caldwell  @dandinu - I have moved `aws-sdk` to peer dependency. please Use [v3.0.0](https://github.com/montumodi/sqs-bulk-loader/releases/tag/v3.0.0) of this library.

**Comment by dandinu** [comment]
Already pulled it. My bundle size dropped dramatically. Thanks!

**Comment by christopher-caldwell** [comment]
Awesome, thank you!
