### ISSUE TITLE
AWS SDK V3

### ISSUE THREAD

**Issue by bpred754** [montumodi/sqs-bulk-loader#30]
Now that AWS SDK v2 is planned to go into maintenance mode, is there plans to upgrade this library to use AWS SDK v3?

```
 NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
```

**Comment by montumodi** [comment]
Hi @bpred754 
Thanks for your comment. I tried creating a branch to use `aws-sdk` v3. It would obviously be breaking change.

Could you try using  `update-aws-sdk` branch and let me know if it works fine?

https://github.com/montumodi/sqs-bulk-loader/tree/update-aws-sdk

I can publish a major version if everything looks good.

**Comment by bpred754** [comment]
Hey @montumodi, I apologize for the delay. I've just verified that the updates are working for me. Can you please comment here when you publish a new version? Thank you!

**Comment by montumodi** [comment]
Hi @bpred754 

Thanks for confirming that it is working fine. I have now published version 4 of this package. Please see release notes [here](https://github.com/montumodi/sqs-bulk-loader/releases/tag/v4.0.0) and also check the [readme](https://github.com/montumodi/sqs-bulk-loader/blob/master/README.md). Let me know in case of any issue.
